#!/bin/bash

set -e
PROJ="/home/runner/work/android-java-terminal/android-java-terminal"
AAPT="/usr/local/lib/android/sdk/build-tools/31.0.0/aapt"
AAPT2="/usr/local/lib/android/sdk/build-tools/31.0.0/aapt2"
DX="/usr/local/lib/android/sdk/build-tools/30.0.0/dx"
ZIPALIGN="/usr/local/lib/android/sdk/build-tools/31.0.0/zipalign"
APKSIGNER="/usr/local/lib/android/sdk/build-tools/31.0.0/apksigner" 
PLATFORM="/usr/local/lib/android/sdk/platforms/android-31/android.jar"
JAVA_HOME="/opt/hostedtoolcache/Java_Adopt_jdk/11.0.16-101/x64"





echo "Cleaning..."
rm -rf obj/*
rm -rf src/com/example/helloandroid/R.java
mkdir bin



#echo "Generating R.java file..."
# $AAPT package -f -m -J src -M AndroidManifest.xml -S res -I $PLATFORM

echo "Compiling APK..."
javac -d obj -classpath src -bootclasspath $PLATFORM -source 1.7 -target 1.7 src/com/example/helloandroid/MainActivity.java
# javac -d obj -classpath src -bootclasspath $PLATFORM -source 1.7 -target 1.7 src/com/example/helloandroid/R.java

echo "Translating in Dalvik bytecode..."
$DX --dex --output=classes.dex obj
pwd
ls -l



echo "Making APK..."
$AAPT package -f -m -F $PROJ/bin/hello.unaligned.apk -M $PROJ/AndroidManifest.xml -S $PROJ/res -I $PLATFORM
$AAPT add $PROJ/bin/hello.unaligned.apk classes.dex

$AAPT list $PROJ/bin/hello.unaligned.apk
cd $PROJ/bin
pwd
ls -l

echo "ZIPALIGNing APK..."
cd $PROJ/bin
$ZIPALIGN -p -f -v 4 $PROJ/bin/hello.unaligned.apk $PROJ/bin/hello.apk 
cp hello.apk  $PROJ/app/build/outputs/apk/release/
cd $PROJ/app/build/outputs/apk/release/
pwd
ls -l 



echo "Signing  APK...."
cd /home/runner/work/android-java-terminal/android-java-terminal/

printf   "B395b39595" > $PROJ/password.txt
# echo $PROJ/p.txt

#base64 $PROJ/password.txt > $PROJ/passwordb64
#cat  $PROJ/passwordb64


#base64 -d $PROJ/passwordb64 > $PROJ/password.txt
#cat $PROJ/password.txt


echo "keystore64___________\n"
echo $KEYSTORE_JKS | base64 > $PROJ/keystore64
cat  $PROJ/keystore64
echo "keystore.jks___________\n"
base64 -d $PROJ/keystore64 > $PROJ/keystore.jks
cat $PROJ/keystore.jks





#echo $PROJ/passwordb64.txt | base64 -d > $PROJ/password.txt


printf   "TUZ3NE1pWVZBZ0VETUZ3NE1pVmNRa1lHSUNwY09EWklYRGcyWEVZM0lBRUhBVnhCTUZ3NE1pVmNR
akFFWERneUpWeEJRekJjT0RJbCBYRUU0TUZ3NE1oWmZCaUFxWERnMlNGdzRObHhHTnlBQkJ3RmNR
VEJjT0RJV1VBUmNPRElXVERCY09ESVdTREJjT0RJRlhEa3hCZ3NxIFhEZzJTRnc0Tmx4R055QUJE
Q0FCQWx4Qk1GdzRNZ1ZBTUZ3NE1nVThNR1lHSUNwY09EWklYRGcyWEVZM0lBRUZJREJaTURnR0lD
cGMgT0RaSVhEZzJYRVkzSUFFRkREQXJCQlJjUWtVb2V6OVpYRVZDM0lSYVhFSkRYRUk1RmwwUUMx
eERSRFJOSlZ4RVFnSUNKeEFDQVNBdyBEQVlJS2x3NE5raGNPRFpjUmpjZ0FpQUZYREF3TUIwR0lH
QmNPRFpJQVdVREJBRXFCQkJjUmpSNVhFRTJYRGs0WEVNd1hFVXpYRGxEIEVTUmNRMFlQWEVJeEEx
MVZYRU15QkZ3NE1nUmNSREE0WERrM1hFTkdNak5jUWpkY1F6ZGNSVFpjUmtWY1F6Y25YRVl6WERr
eVhFUkIgWEVNd1hEZzF5NlZjUmpVOFhFSXp4SkVWWERrNVhFUTFQbmhjT0RoY1JUQmNRMFhNZ3o0
aUQxeEJSbHc1T0Z4Rk4xeEZRMDkwZUUxYyBPVFZjUkRnb1hFRkVYRVEzTEZ4Qk5sdzVRVnhFTXhB
NFB3RmNRVGZXaUgxY1FUQmNRalJjT1VaY1JFSmNSRGNjWERneHk1OFRNbHc0IFExeEJSbHhHTlZ4
R05XTkxIM1JjUWtNekRseENNMXc1UWtWY1JqUjhYRVV4WEVSR090eWRmbXdDWEVSR1h3OHFJRnhG
TmlCSFhFTXggeXBsSFhFSXlBc3l2SjF4R1JDQm5FRnhCUkI0cVoxdzRRVnc0TWx4R01WdzVOVnhG
UW40MlpVMWNPVFJHSkZ3NU9Ed1RKa1pjUlVaYyBRa2JKclZ3NE4xd3dNRnhETjF4R1FoQmNRMEZT
SUROY09UaGNPRU5jUVViSXR6MGlBVnhHTmdNVkoxeEJReXM4WEVFMlhFVXplMXhHIE56UERxRnc1
TjF3NVJWeEdOQ0JZWEVVejJLdGNSVGhjUWtOTVhFSkRYRVJFWEVZME1VdFlYRVE0WEVRd0hpaHR5
WVJRWEVWRlVDOWMgTURCY1JEUTBTbHhCUmdjOGUzQmNRVGtPYWx4R01WdzVOVnhCTjF4RVExeEVR
blVQWTJkVlhEazRjVDRoMjdjcFhFSTVYRVE0Tkc1YyBSVEpOUEZ4Qk1oZ2hYRU16WEVNd0dHQW9Y
RU13VGx4RU5WNGdMVHRDV201Y1JqRWZYRGsxWEVaRlhEbERMbHhFTUZ4RVFWdGNSRVZGIFhFTTFZ
UzV1RVZ3NE16UmNPVGh2WEVJMlhFSTFYRVl5WERneVhFUTBhVnhETWxSR0dDQVhYRGhGWERoREVs
SmNSVVVDWERneFhFVkQgWEVZM0hGeERSRnhGUWljZ1hFWXlYOXl2WERsRWRGeEdSRnhDTnpCY1F6
QVhJVnc0TUZ3NVJHOGRYRU15WEVORkpsdzRObHc1Tmx3NSBSQVFjRWx4Rk9HeGNRa0pjT0VWY1JU
VmNPRVpjUkRjd1hEazJYRVUzWEVJMVRWdzVRMkVqWERsQlhFSTRFbHhDTUZ4R01CbGNPVE5NIFhE
aEJYRUUyTWx4RU4xNWNRMFV3WEVKRVhEQXdJQlV2RDF4RlJseEdRVUJjT0RoY09VRmNSamMwWEVS
RVRrQWFmMXhHUWwxY1JVRmMgUlRKY1F6blJ2R3A1VlRaWkgxeEVPRnhHUVZ4Qk5pc09YRUV6WEVV
eVRWdzRNdHVPTmxSY09VTkVMaVpjUTBFUkhqZk1nT21Vb2x4RSBOMVZRWERrMFdsdzROWGg3SGxB
K0lseEVPT3VGcUZ3NE1WeEJNVnhETTF4Rk1WdzRRVnhETnlkY1FUQk1YRGxFWEVFM1hFSTBPVnc0
IE9GdzRNaFZjT1RsY1FVSmNSRFFyZlYxZkx6bGNRa0VqSDJCT1hFSkdFVnc1UmtNZFhFRXlQMXc1
TWx4RFJUSmNPREJjUlVKY1JrTjcgWERnMVhEa3lYRGswUlZ3NU9GeERNbEJhWEVKQ0QxdzRRbHhG
Um45Y1FUWUVYRVpEWEVZMklWY1lYRGt3REZ4R055YzRQbHhjUVRkcyBNbHc1UlZ4Rk5OT2xYRU0w
WEVNMlhFWkdYRGhDSHlwY1FVSUhJRTFoYjF4RlExeENSSFJjT0VGY1FUVkRjVnhFUXdZckpsdzRN
bHhDIFFVODNYRUV6R1IwZ1hEZ3daMXhETlVWY1FUUlJURnhDUmx4RE5zdVJGMXhETkhSM01GeEVP
VWROWERrNUVIazFiMXhDTitleW1HTmMgT0VSMFhEazRYRU0xNXBhVVhFRkRYRGxEY2pwY1JURmNS
RU1MWERBd2IwZ3RDRnhHTTF4RFJGMWFYRVUzSjA5YlhFVXpYRVV5WEVVNCBNUVlwWEVSQlFDRWhY
RGxHWEVKRVhEbERPd2hjT0RrN1hFTXdPamRjT0RSSFZ5VjZYRUpEZkZ4Q1FobDR4YmhmWEVJeEpY
RVRYRU15IEdseENRbHc1TkZ3NU1seEJObHc1T1ZKY1JUaGNReklnWEVKR1hFVkNFbUJjT1VKY09U
bFpVVnhCTmx3NE9EWmNSRUpOWEVRMFhFVXkgSlZ3NU5jZWNZMjlzWFZ4Rk5Gc0lVOEt4WFZ4Q05E
ZlpvOGV2WERreFhFWTRRMXhETWx4RlJoNWNPVFpjT0RKY09FUmNRa0ZSWEVVeCBYRVpDWERoQlhF
RkJYRVEwY0JZOVhEZ3hYRGs0WERsRFhFRTFYRGhFMTR3K1hFRTNYRVpEWEVVNFhFVTNmMlRQbFNV
c1FUaGNPVU5jIFJqVjZKQkZjUmtZeFhFTkdYRU5GTnhwZU5seEZObE5UVFZ4Q1EyVlRYRUpHVDF4
Qk04bWRCVnhFTkNBc1hFWXhiU1lMYkZGY1F6RGUgZzF4R05sVTNYRVZDRWwxL1hFWkdYRUkxWkR3
c1hFTkJYRnc0TVMxY1FqTTRYRVF3QmdVRlBFdzFYRGt5R3RLcFhFTXdVVlpjUWpaYyBSa0ZZRkZ4
RE1seEROd1JjUkRCS1hEa3pYRVExNEtpZ1hFUXpYRVl3TUZ3NU4xeEZOMXhFUXd0Y09VVURNMllX
RHh0Y09FSTJBbWJyIGpyZ2FSOTJTWEVWRUhGeEJNVnhDTmhaYlhFSTBNaGd5QjF4RVF3Y3lYRnc0
TnhKY09UZGNSVFoyWEVVNVhEZ3lCMmxMYkdKY09UaGMgUmpOY1JUZ2dYRGhCUTFSY1F6VVpabHhG
UlZaMlhFWTVLbk5jUlRORmVUdGNRVVpjT0RGY1JEUnVYRGhFWDF3NVJuVmNSakVjY1Z4RSBNbHhF
TlE5TlhFSTJYRGs0WERnNFhFVTBUK0dabFZ4RU1pNU9YRVZHUkZ4R1JseERSWFJuWERoQllseEVP
RnhGTnR1NlhFTTJEbHhHIFJHTXlYREF3YVZ4R1JkR2JYRGd3WEVFM2V5b2ZNbHc1TXlnT0ZseEVO
em4wajRhd2N5anB0NFlNTDF3NVJ0eUdTUlpFS0Z4Q1FWeEMgUTlpVlVVOWNSVEZiQTF4R1JGeEdO
MXhHUmx3NFExNWJYRUV6V1hnYlhFWTFKbHhCTXlCY1JFVS9YRVJESUZ4R1FVM2V1Rnc1T1hITSBy
ME1iZDFaY1JEVmFYRUpGWEVZd1hFVTJjeDBRWEVaQ0dGeEZSV2xESlZ4R05GeEROVnhFUTF4R1Js
eEVOeVU3YTF4Qk0xd3dNRmRUIFVsdzRPQ2RlYUVaY09UaGNRekpjWDF4R09RdGNRVE1ZWERoRWRW
eEJOVnc1TlZ4RU5WeEdOVnc0TTF3NFJGeEVObHhGTWx4RE1pMWMgUkRCY1F6VmNSRVpjUmpaY1JU
Wk9YRUk1WEVGQ1hFVTNLWFBYdVdsY1JqWjlGVnhHUlZ4RlF3SmNRemNFTmhaY1JUTmNSa1FwRzFG
ZiBhWDRrWEVFelhFUTJIMjBsWEZ3NVJEUXVYRUV3WEVaQ3c3OFRRZ0l2WERnMFhFUkdIVnhHTTB4
Y1JrTnBYRUpHWERrNVhFRkRYRVEzIFgxdzRNRnhCTTF4Q09GeERNVnhCUlFVaFhFWTJQUVZWZDJO
UVhFRXdkeUFCekkxY1JUY1BYRUUxWERnMFhFSkVYRUUzWEVZeFVoUTcgWEVSQ1cxdzRObGRjUkRk
TlhEQXdYRGt3QlRNZFlGeEZSR1FIWERreklCSmNPVEpSTzBSUVhFTkdEMkJNWEVWQmZINHJYRVZE
TnlGYyBRMFJjUXpBaUZIaGNSVFF2WEVSRUhWeEdOQVJEQlZ3NE1seEVPSExTdWx4RlEyeGNPREZj
T0VVQ0JseEVSRjFjUkROY1JqVmNPVUlSIFhFTkNlek5jUmpRV0FUbktsbHhGUkVNVlhFVkZTbU1Y
WEVVeFBGeGNRVUpQWERoRkhWaGNSVFpjUTBSclJWeENRbmxjUlRCY1JVUVggTVQ0d0dRWWdLbHc0
TmtoY09EWmNSamNnQVNBVU1Rd2VJRnd3TUcxY01EQjVYREF3YTF3d01HVmNNREI1TUNFR0lDcGNP
RFpJWERnMiBYRVkzSUFFZ0ZURVVCQkpVYVcxbElERTJOakU1TlRBNE5qQTNOREV3WERneUJWdzRN
d1lMS2x3NE5raGNPRFpjUmpjZ0FRd2dBUUpjIFFUQmNPRElGTURCY09ESUZMREJtQmlBcVhEZzJT
Rnc0Tmx4R055QUJCU0F3V1RBNEJpQXFYRGcyU0Z3NE5seEdOeUFCQlF3d0t3UVUgWEVZeFhEazJY
RU13WEVNeVhEQXdYRVJFTzBoY01EQmNRVVZTWEVVMVFGeENNVnhHT0djVlhFRXhYRU13WEVGQkFn
SW5FQUlCSURBTSBCZ2dxWERnMlNGdzRObHhHTnlBQ0lBVmNNREF3SFFZZ1lGdzROa2dCWlFNRUFT
b0VFTnVPWEVFd1VGeENOVnc0UkY4eFhFWkdIak5QIFhFSXpYRVkyS2x4Qk5RUmNPRElFWEVNd2Ru
c2tRRnhDTm1KY1JEVFBueWxBWEVFeFJRVmNSVFZ1WEVFM2JseEVObHhFUkJsaEFqZGQgWEVRNVhF
UTVFREJ3ZVRCblhFRkdEa0pjUVRJZ0lWdzVRekpjUlROWFBGeEROaWxjUlRaY09EWExwRnc1Tmx4
R09GMGZYRGxEWEVOQiBHM25ackdGbVhFRXlYRGd4WERoQ1hFVkVmUVJjUmtNNEtrOElYRU14WERn
NWQzTmNRMFpjUmpKY1JFTUhQQzFkWEVWRlhEaEV3NjVMIDNZQkpSRnhHTkE5RFhFRTBYRGxDWEVJ
eVhFSkdYRVpDWEVZNVhWeEROaGc0WEVVeVNSeGNPRUpjUlVSY1EwSTNYRVZHWERrd2JCZGMgT0VS
Y1FUZzZTMXhEUkZ4RlJGeENORnhHUlJFN0xseENSa2NvY3lGY09FTmNRekJjUWpOUkFVell0a1pj
T1RreVhFUkNYRU5FMDZKaCBYRVF4WEVOQ1hFVkdYRVJFWEVWQ0wxdzVNZzVjUmpNcEFseEVSR1Jj
T1VKNlhFSXhYRVJHYUY5aU5WdzRRa2NlSUZ4R09GeEJORnhCIE1ERjBmRnhHTlZ3NE1XTmNPVFpj
UWtOd2NFa1pDRnhDTWx4Q1FYdHFRRzFyU1dvalhFSkR6cUptSUhRL0lGeEZPUUlRWEVNek15UmMg
UmpsOVhFTXhYRVl4TDF3NE9FeGNRVE5QWEVORlhFVTFYRGsxTWw0VDBZNWNSVFJjT0VVclhFTTJa
VnhHTXlaVWVGeERRbmxCWEVGRiAzYTVjT1VGc1hFRkdYRVF6VzFFUUVWeEdOVnhDUTM1Y09EZ2ZR
MXhEUmh0Y09FWUVYRU5FVzNOY1JFUkhmVnd3TUJNRzZyNjdYRUZGIFhFRTVBVnhCTXpOT1hFWTVY
RU0xMTcxY1FqRmNSVEY3WEVFM1pWdzVNRDkvWERrMlhEaEJCbHhDTXpsY09FWmNPREpjUVVFK1hF
RTIgRHhGY1EwUTJYRVJCTFFGY1FUUXQxSkZjUVRRWVhFWkdJbHhETU5tMlhFWXdPR0ZjT1VaZGZG
dzROd2hjUWtKY09Ea1lYRUkzWEVFMiBJU25HcDF3NFExeEZORVpPWEVOR0tWeEVSdDJYVlU4cFlW
eEdSRnc3Zmx3NVJWeEJRVjFjUmtGY09UWURYRVpDWEVWRkVoUGV0VVpjIFF6ZlJrRnc1TVFkY1JE
WTNhRnc1UThPMVJuWmNRemhjUlRkR0JDUmNRa1ZXWkFGY09UVnJYRUU1WEVNNGYyaERYMXhCT1dW
Y1F6RUwgYWx4R09WeENNdDZKWERnMlhFRTBmMXhFUkQxY1FqTmNSVUp4WEVVMk5GdzVNakZxWERs
R0puNWNRVGh5WERsRVBIQmNPRVZjUVRRbiBjVnc0T0NWY1JrRkFhV2g5WEVRMGRWdzVOMXhHUmx4
RFFoMWNRVVpjT0RCY1F6TThYRVpGU1Z4R09GeEROVzVkVTI0elhFVTNibHhEIE5sUTRJRnhETkZ4
RVFWeEROUkZjUlVWY01EQmNRVUZjT0RaY1JVRmNRVGhYRTF4R09VSmNRakk0WERnMVhFVXpMRnhH
UVY1Y1JUZ0ggVFZ4RE1NNk96NU5jUkVKY1JqRlJEMEZPWDBsMFYxeEVNRk5jUkRBeFhFUTFUR2RX
WERneFlIRk0xNmxDWms4b0JGdzRPRnc1TWdFQyBEMk5IRlZ4Qk1seENNMXhFUkE1S1prQWN3cTVj
UmpKY1F6QmNPVU1kWEVGR0ZGeEZOMEo4WEVFd1hFRXpYRU0xWEVVd0ZseEVSR0YvIFhFTkJiMzFj
T1RWY1FVTnRaeGxjUkRoVlhFSkN4YUExWERrNFhFVXdYRVEwU1ZaL0hGeENORjlhWEVJd1hFTkYw
YkpjT0RWY09ESmggZkJ4Y09EbGUwcU5jT0Rrd1hEa3dXMXc1T1V4Y1JUZGNSRG5FbVZ4R1F3ZGNS
alJjUkVOdHk2VkdYRVF5WTF3NU1uSmNRakZmWEVWQiBYRUk0ZjF4RE9WdGNSa1RLb0RaY1JrRmNS
RFpEZWx4Qk14QTNYRUZEWEVNekJGeEdSVnhEUVZ4R09VTmNRems3WERrNUFqdHRMUkZjIE9ERkpY
RU0wWEVRME5FdGNPRE01SDAxY1JEZkVnQ05VWEVaRlZEdGNPRUoyZGx4Q1FWeEJObHhFUVE5Y1JF
TlpWRnhGTW1oY1JUZGMgUkRrRFBGeENNVnc0TlZ4Rk0xeEdNMWxjUVROY09ERk9UMlY0WEVWRVd6
VmNPRFpjUkRja1dGdzVRbHhGUkVOY1FrSmNRVG5UaEZ4RSBRMVZMWEVFMVhFRTJkVnc0TVZ4R05p
QmdJRnc1UWx3NE5sdzRNRnhFUlhSY1FUZGNRMFJjUlVGRFhFUkRZMXhCTmx4Rk55dGNSak5zIEpR
eGNRalVIWEVFeFhFVTFDeGRjT1RZbFhFWkdYRUl6WERsRVhFSkVNeFJjUlRkY1EwTmNSamhjUlVa
Y1F6QU1MRnhHTkY5dlhFSkMgWDF4Qk9XdytYRUpFWERnM1hEazJYRVV3TEZ4RE9UWi9YRGc0WERo
QlhFTTBFMk45SUZ4RlFseEVNK3V6dXpVeVhFUTNaRnc0T1Z4QyBP***Cg==" > $PROJ/keystore.jks


# base64 -d  $KEYSTORE_JKS > $PROJ/keystore.jks



# non work printf $KEYSTORE_JKS > $PROJ/keystore.jks



#cat $PASSWORDB64
echo "keystore.jks_____________/n"
cat $PROJ/keystore.jks
echo  "____________/n"
cd /home/runner/work/android-java-terminal/android-java-terminal/
pwd
ls -l
chmod +x $PROJ/password.txt 
cat $PROJ/password.txt

$APKSIGNER sign --ks    $PROJ/keystore.jks    $PROJ/app/build/outputs/apk/release/hello.apk  <  $PROJ/password.txt          
$APKSIGNER verify -v  -v4-signature-file $PROJ/app/build/outputs/apk/release/hello.apk.idsig $PROJ/app/build/outputs/apk/release/hello.apk 
















echo "Making AAB..."

echo "Compile resourses..."
$AAPT2 compile --dir $PROJ/res/ -o $PROJ/obj/res.zip

echo "Link resourses..."
$AAPT2 link --proto-format -o $PROJ/obj/linked.zip -I $PLATFORM --manifest $PROJ/AndroidManifest.xml --java src $PROJ/obj/res.zip --auto-add-overlay

echo "Compile the Java sources to bytecode"
#javac -d obj -classpath src -bootclasspath $PLATFORM $PROJ/src/com/example/helloandroid/*.java
javac -d obj -classpath src -bootclasspath $PLATFORM -source 1.7 -target 1.7 src/com/example/helloandroid/MainActivity.java
echo "Convert the bytecode to Dex format (Dalvik Android virtual machine)"
$DX --dex --output=bin/classes.dex obj

echo "Combine the resources and the bytecode into a single bundle"
cd $JAVA_HOME/bin
pwd
ls -l

cd $PROJ/obj
$JAVA_HOME/bin/jar  xf $PROJ/obj/linked.zip resources.pb AndroidManifest.xml res
mkdir manifest dex 
mv AndroidManifest.xml manifest
cp ../bin/classes*.dex dex/ 
echo "jar cmf"
$JAVA_HOME/bin/jar cMf base.zip manifest dex res resources.pb

echo "Build the AAB"#
wget https://github.com/google/bundletool/releases/download/1.11.2/bundletool-all-1.11.2.jar 
pwd
ls -l
echo "Java -jar bundletool"

$JAVA_HOME/bin/java -jar bundletool-all-1.11.2.jar build-bundle --modules=base.zip --output=../bin/hello.aab
cd $PROJ/bin
pwd
ls -l




echo "Sign AAB"
$JAVA_HOME/bin/jarsigner --help
cd $PROJ/bin
echo "jarsigner....."
cat $PROJ/password.txt
cat $PROJ/keystore.jks
$JAVA_HOME/bin/jarsigner  -keystore $PROJ/keystore.jks      $PROJ/bin/hello.aab alias1  < $PROJ/password.txt

















