name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    


    
    
jobs:
 
  build-with-upload-artifact:
    runs-on: ubuntu-latest
      
    steps:
        

    
    - uses: actions/checkout@v3
    
    
   

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
          java-version: 18.0.2+9
          distribution: 'adopt'

    - name: Android JDK install and apk build
      run: |
             sudo apt-get install libc6-dev-i386 lib32z1 openjdk-8-jdk
             pwd
             ls -l 
             chmod +x build.sh
             ./build.sh
        
        
    - name: Upload APK
     
      uses: actions/upload-artifact@v2
      with:
           name: hello.unaligned.apk
           path: /home/runner/work/android-java-terminal/android-java-terminal/bin      
           
           
    
    - name: Releasing using Hub
      uses: ShaunLWM/action-release-debugapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: app
       RELEASE_TITLE: New Build
  
  
  
  
